import { Inter } from 'next/font/google';
import './globals.css';
import ContextProviders from '@/context/ContextProviders';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link rel="stylesheet" href="https://static.filestackapi.com/transforms-ui/2.x.x/transforms.css" />
      </head>
      <body className={inter.className}>
        <ContextProviders>{children}</ContextProviders>

        <script src="https://static.filestackapi.com/transforms-ui/2.x.x/transforms.umd.min.js"></script>
      </body>
    </html>
  );
}